
spring:
  application:
    name: Server1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/yun6
    username: root
    password: root
mybatis:
  type-aliases-package:  com.lxj.pojo
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:9001/eureka
